version: 3

method:  timestamp


tasks:

  generate:
    desc: Generate whatever configured by Go generate feature
    cmds:
      - go generate ./...

  snapshot:
    desc: Build a local single-target snapshot
    cmds:
      - go run github.com/goreleaser/goreleaser@v1 build --snapshot --single-target --rm-dist
